name: Publish docker image, push into the catalog and update the deployed application
# https://github.com/napptive/cd-example/blob/main/.github/workflows/deploy-app.yml
# TODO: WIP
on:
  # push:
  #   branches: [main]
# Uncommment this to launch the workflow manually.
  workflow_dispatch:

env:
  PLAYGROUND_PAT: ${{ secrets.PLAYGROUND_PAT}}
  PLAYGROUND_ACCOUNT_NAME: napptive # TODO: Change with your Playground account name.
  TARGET_DOCKER_REGISTRY: napptive # TODO: Change this with your docker account name.

jobs:
  build:
    name: Push docker images
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_HUB_USER}}
          password: ${{secrets.DOCKER_HUB_TOKEN}}
      - name: Build and push Docker images
        run: make docker-push
      - name: Render Kubernetes OAM files
        run: make k8s
      # Create a cache with the generated files
      - name: Uploading manifest
        id: cache-k8s
        uses: actions/cache@v2
        with:
          key: k8s-yaml-${{ github.sha }}
          path: ./build/*
      
  check-app:
    needs: build
    name: Check if the app are deployed
    runs-on: ubuntu-latest
    outputs:
      not-found: ${{ steps.not-found.outputs.not-found }}
      found: ${{ steps.found.outputs.found }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Check if the app exists        
        uses: napptive-actions/playground-github-action@v2.2.4
        continue-on-error: true
        id: check
        with:
          cmd: "apps info cd-example"
      - name: Set App not found
        id: not-found
        run: echo '::set-output name=not-found::true'
        if: steps.check.outcome != 'success'
      - name: Set App found
        id: found
        run: echo '::set-output name=found::true'
        if: steps.check.outcome != 'failure'

  push-to-catalog:
    needs: build
    name: Push the application to the catalog
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Get k8sfiles
      uses: actions/cache@v2
      id: cache-k8s
      with:
        path: ./build/*
        key: k8s-yaml-${{ github.sha }}
    - name: Get Version
      id: version
      run: echo "::set-output name=version::$(cat version)"
    - name: Push the application on the catalog
      uses: napptive-actions/catalog-push-action@v2.2.4
      with:
        applicationPath: ./build/k8s/
        namespace: ${{ env.PLAYGROUND_ACCOUNT_NAME }}
        applicationName: "cd-example"
        tag: ${{ steps.version.outputs.version }}

  update-app:
    name: Update application
    needs: check-app
    runs-on: ubuntu-latest
    # if the application aready exists -> update it
    if: ${{needs.check-app.outputs.found == 'true'}}
    steps:     
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Get k8sfiles
      uses: actions/cache@v2
      id: cache-k8s
      with:
        path: ./build/
        key: k8s-yaml-${{ github.sha }}
    - name: Make scripts executable
      run: chmod +x ./scripts/*.sh
    - name: Get Kubeconfig      
      uses: napptive-actions/playground-github-action@v2.2.4
      with:
        cmd: "get-kubeconfig" 
    - name: Get Version
      id: version
      run: echo "::set-output name=version::$(cat version)"
    - name: Deploy new version of the application
      run: ./scripts/update.sh
      env:
        VERSION: ${{ steps.version.outputs.version }}

  deploy-app:
    name: Deploy application from catalog
    needs: [check-app, push-to-catalog]
    runs-on: ubuntu-latest
    if: ${{needs.check-app.outputs.not-found == 'true'}}
    steps: 
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Get Version
      id: get-version
      run: echo "::set-output name=version::$(cat version)"
    - name: Set catalog qualified application name
      id: appname
      run: echo "::set-output name=appname::${PLAYGROUND_ACCOUNT_NAME}/cd-example:${{ steps.get-version.outputs.version }}"
    - name: Deploy the app from the catalog
      uses: napptive-actions/catalog-deploy-action@v2.2.4
      with:        
        appName: ${{ steps.appname.outputs.appname }}